---
workspace:
  launch:
    button:
      name: 🛫 take off
      description: 💪 Gradually moving towards the four modernizations of operation and maintenance - standardization, standardization, efficiency and elegance
      hoverImage: .cnb/src/qifei.gif
    cpus: 8
    disabled: false
    autoOpenWebIDE: false

issue:
  button:
    description: 🙋🏻‍♀️ I Have A Question
    hoverImage: ".cnb/src/jushou.jpg"

fork:
  button:
    description: 🫵 You are very sensible, young man
    hoverImage: ".cnb/src/trump.gif"
