---
blank_issues_enabled: false
contact_links:
  - name: 📜 Official Documentation | GO Ldap Admin Doc
    url: http://ldapdoc.eryajf.net
    about: The functional usage and design considerations of the project will be presented on the official website. Please read the official document before submitting the question. If it is not satisfied, then ask the question.
  - name: 👀 Github论坛 | GitHub Discussions
    url: https://github.com/eryajf/go-ldap-admin/discussions
    about: If your problem is not a feature or a bug, go to the discussion panel and retrieve if your problem already exists before submitting.
